export const TRANSLATIONS = {
  it: {
    title: 'Calligraphy & Font Art Editor',
    subtitle: 'Crea, personalizza ed esporta scritte in corsivo elegante e decorazioni swash per Cricut, stampa o design.',
    addText: 'Aggiungi Testo',
    addSwash: 'Aggiungi Tratto (Swash)',
    addFrame: 'Aggiungi Cornice',
    addSparkle: 'Aggiungi Dettaglio',
    textSettings: 'Impostazioni Testo',
    swashSettings: 'Impostazioni Tratto',
    frameSettings: 'Impostazioni Cornice',
    sparkleSettings: 'Impostazioni Dettaglio',
    canvasSettings: 'Impostazioni Canovaccio',
    presets: 'Modelli Pronti (Presets)',
    layers: 'Livelli (Layers)',
    noLayers: 'Nessun livello attivo. Aggiungi il tuo primo elemento!',
    exportTitle: 'Esporta Progetto',
    exportFormat: 'Formato Grafico',
    downloadBtn: 'Scarica File',
    copiedSvg: 'SVG Copiato negli appunti!',
    copySvgBtn: 'Copia Codice SVG',
    textPlaceHolder: 'Inserisci scritta...',
    fontSize: 'Dimensione Carattere',
    letterSpacing: 'Spaziatura Lettere',
    rotation: 'Rotazione',
    scale: 'Scala',
    opacity: 'Opacità',
    color: 'Colore',
    strokeWidth: 'Spessore Linea',
    backgroundColor: 'Colore di Sfondo',
    gradientColor: 'Secondo Colore (Gradiente)',
    gradientAngle: 'Angolo Gradiente',
    bgType: 'Tipo Sfondo',
    bgSolid: 'Solido',
    bgGradient: 'Sfumatura (Gradiente)',
    bgTexture: 'Texture Carta',
    textureWatercolor: 'Carta Acquerello',
    textureLinen: 'Lino Elegante',
    textureChalkboard: 'Lavagna Nera',
    textureKraft: 'Cartone Kraft Grezzo',
    textureNone: 'Liscio / Bianco',
    canvasPlaceholder: 'Canovaccio',
    deleteLayer: 'Elimina Livello',
    duplicateLayer: 'Duplica',
    deselect: 'Deseleziona tutto',
    moveGuide: 'Trascina gli elementi nel riquadro per posizionarli',
    instructionsTitle: 'Come usarlo:',
    instructionsText: '1. Seleziona un modello o scrivi la tua frase. 2. Aggiungi i tratti decorativi (swash, cuori o onde) e trascinali per agganciarli alle lettere. 3. Personalizza spessori e sfondi. 4. Esporta in SVG vettoriale (ideale per plotter da taglio) o in PNG ad alta risoluzione!',
    presetsDesc: 'Seleziona un punto di partenza creativo ispirato ai migliori stili calligrafici:',
    bold: 'Grassetto',
    italic: 'Corsivo',
    fontCategory: 'Stile Carattere',
    width: 'Larghezza',
    height: 'Altezza',
    applyPreset: 'Carica Modello',
    customTextLabel: 'Contenuto Testo',
    resetWorkspace: 'Svuota Tutto',
    vectorAlert: 'Nota: L\'esportazione SVG include le definizioni dei Google Fonts per rimanere vettoriale modificabile al 100%.',
    feedbackMessage: 'Seleziona un elemento sul canovaccio per sbloccare i cursori di precisione.'
  },
  en: {
    title: 'Calligraphy & Font Art Editor',
    subtitle: 'Create, customize and export elegant script writing and swash decorations for Cricut, print, or digital design.',
    addText: 'Add Text Layer',
    addSwash: 'Add Swash Curve',
    addFrame: 'Add Crest Frame',
    addSparkle: 'Add Sparkle Detail',
    textSettings: 'Text Typography',
    swashSettings: 'Swash Line Shape',
    frameSettings: 'Frame Geometry',
    sparkleSettings: 'Sparkle Details',
    canvasSettings: 'Canvas Board Settings',
    presets: 'Starter Templates',
    layers: 'Canvas Layers',
    noLayers: 'No active layers. Add your first design element!',
    exportTitle: 'Export Art',
    exportFormat: 'Graphic Format',
    downloadBtn: 'Download Graphic',
    copiedSvg: 'SVG XML copied to clipboard!',
    copySvgBtn: 'Copy SVG Markup',
    textPlaceHolder: 'Type lettering here...',
    fontSize: 'Font Size',
    letterSpacing: 'Letter Spacing',
    rotation: 'Angle Rotation',
    scale: 'Scale Magnification',
    opacity: 'Opacity Transparency',
    color: 'Color Tone',
    strokeWidth: 'Line Weight (Stroke)',
    backgroundColor: 'Primary Background Color',
    gradientColor: 'Secondary Gradient Color',
    gradientAngle: 'Gradient Angle Degree',
    bgType: 'Background Finish',
    bgSolid: 'Solid Color',
    bgGradient: 'Ambient Gradient',
    bgTexture: 'Paper Texture',
    textureWatercolor: 'Artistic Watercolor Paper',
    textureLinen: 'Elegant Linen Cloth',
    textureChalkboard: 'Vintage Blackboard',
    textureKraft: 'Rustic Kraft Cardboard',
    textureNone: 'Flat Matte',
    canvasPlaceholder: 'Design Stage',
    deleteLayer: 'Remove Layer',
    duplicateLayer: 'Clone Element',
    deselect: 'Clear Selection',
    moveGuide: 'Drag elements directly on the canvas preview to align them',
    instructionsTitle: 'Editor Guide:',
    instructionsText: '1. Choose a starter layout or type your phrase. 2. Feed decorative curly heart or wave swashes and drag them into place at the letter ends. 3. Fine-tune colors and line weights. 4. Export to vector SVG (for cutters) or high-res PNG!',
    presetsDesc: 'Load handcrafted designs featuring wedding, stationery, and branding styles:',
    bold: 'Bold Serif',
    italic: 'Slanted Outline',
    fontCategory: 'Typography Category',
    width: 'Viewport Width',
    height: 'Viewport Height',
    applyPreset: 'Apply Template',
    customTextLabel: 'Inscribe Text',
    resetWorkspace: 'Reset Canvas',
    vectorAlert: 'Notice: SVG exports encapsulate modular Google Web Font declarations to maintain infinite mathematical scalability.',
    feedbackMessage: 'Click directly on any layer inside the canvas area to expose granular sliders.'
  }
};
